resilience4j.retry:
  configs:
    default:
      max-attempts: 5 # ?? ??? ? ??? ? ???
      wait-duration: 1000 # ?? ?? ??? ? ????(milliseconds)
      retryExceptions: # ? ??? retry ??
        - com.example.resil.exception.RetryException # RetryException? ??? ??? ??? ??
      ignoreExceptions:
        - com.example.resil.exception.IgnoreException # IgnoreException? ??? ??? ??? ??x
  instances:
    retryConfig: # config ????? ?? ?
      base-config: default
###### Retry? ##### CircuitBreaker ? #####
resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-type: count_based # ?? ??? ???? ???? open ??? ????, ???? vs ????
      minimum-number-of-calls: 5 # ?? 5? ???? ???? ??? ??? open?? ???? ??.
      sliding-window-size: 10 # ?? ??? ?????? ? ???? ?? 10?? ?? ? ??? ??

      record-exceptions:
        - com.example.resil.exception.CircuitBreakerException
      ignore-exceptions:
        - com.example.resil.exception.IgnoreException
  instances:
    circuitBreakerConfig:
      base-config: default

